dist: xenial
language: python
python:
    - "3.6"
    - "3.7"
os:
    - "linux"
addons: firefox: latest
install:
    - "pip install pipenv"
    - "pip install codecov"
    - "pip install pytest pytest-cov"
    - "pipenv sync"
script:
    - pytest --cov=./
after_success:
    - codecov
